#!/bin/sh

. /Applications/mampstack-8.1.9-0/scripts/setenv.sh
SASL_PATH="/Applications/mampstack-8.1.9-0/common/lib/sasl2"
                export SASL_PATH
exec /Applications/mampstack-8.1.9-0/common/sbin/.saslpasswd2.bin -f "/Applications/mampstack-8.1.9-0/common/etc/sasldb2" "$@"
